// Generated by scripts/export_device.py — do not edit by hand.
#pragma once

#define VB_N 16384
#define VB_LOG2N 14
#define VB_FS 12000.0f
#define VB_DECIM 16

#define VB_TOL 0.02f
#define VB_BP_NSEC 4
#define VB_BP_PAD 27

#define VB_DEC_NSEC 4
#define VB_DEC_PAD 27

// CWRU 6205 drive-end geometry
#define VB_GEO_N 9
#define VB_GEO_D 0.3126f
#define VB_GEO_PITCH 1.537f
#define VB_GEO_PHI_DEG 0.0f

static const float VB_BP_SOS[4][6] = {
  0.0939808514f, -0.187972945f, 0.0939920946f, 1.0f, -0.298088277f, 0.121978721f, 1.0f, 2.00000002f,
  1.00000001f, 1.0f, 1.03013908f, 0.324369116f, 1.0f, -1.99988037f, 0.999880382f, 1.0f,
  -0.767318994f, 0.599256574f, 1.0f, 1.99999998f, 0.999999988f, 1.0f, 1.4993698f, 0.745027609f
};

static const float VB_BP_ZI[4][2] = {
  -0.0939808506f, 0.0939920945f, 5.70570156e-10f, 3.66523104e-10f, -1.38698994e-09f, 1.38682404e-09f, 2.77732307e-18f, 9.71423751e-19f
};

static const float VB_DEC_SOS[4][6] = {
  9.08016771e-11f, 1.81603354e-10f, 9.08016771e-11f, 1.0f, -1.88681752f, 0.890978772f, 1.0f, 2.0f,
  1.0f, 1.0f, -1.89638731f, 0.906951371f, 1.0f, 2.0f, 1.0f, 1.0f,
  -1.91715546f, 0.936996254f, 1.0f, 2.0f, 1.0f, 1.0f, -1.95064631f, 0.977451554f
};

static const float VB_DEC_ZI[4][2] = {
  8.71922043e-08f, -7.76765038e-08f, 3.29617483e-05f, -2.98865813e-05f, 0.00662979586f, -0.00621001167f, 0.987597229f, -0.965178209f
};
